apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: maor30levy/movie-app-client:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: CLIENT_PORT
            - name: REACT_APP_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: REACT_APP_SERVER_HOST
            - name: REACT_APP_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: REACT_APP_SERVER_PORT
