apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: web
          image: maor30levy/movie-app-movies:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MOVIES_PORT
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MONGO_PORT
            - name: MONGODB
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MONGODB
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: JWT_SECRET
