apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: web
          image: maor30levy/movie-app-server:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: SERVER_PORT
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: AUTH_PORT
            - name: AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: AUTH_HOST
            - name: USERS_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: USERS_PORT
            - name: USERS_HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: USERS_HOST
            - name: MOVIES_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MOVIES_PORT
            - name: MOVIES_HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MOVIES_HOST
