apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: web
          image: maor30levy/movie-app-users:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: USERS_PORT
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MONGO_PORT
            - name: MONGODB
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: MONGODB
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: dev-env
                  key: JWT_SECRET
